services:
  db:
    image: postgres:16-alpine
    container_name: catalog.db
    restart: always
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: catalog.pgadmin
    restart: always
    ports:
      - "8881:80"
    env_file:
      - .env
    volumes:
      - catalog.pgadmin-data:/var/lib/pgadmin

volumes:
  catalog.pgadmin-data: